version: '3.7'
services:
  cpu-node:
    build:
      context: .
      dockerfile: Dockerfile
    # 'volumes'maps the src directory in your workspace to the src directory in the container,
    # so that changes to your local files are reflected in the container.
    volumes:
      - ./src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket

    environment:
      - "ROS_MASTER_URI=http://10.42.0.1:11311"
      # This is the ip of cpu_node. we need this to communicate with nodes in other container
      - "ROS_IP=10.42.0.1"
      - "ROS_PACKAGE_PATH=/app/src"
      - "DISPLAY=${DISPLAY}"  # Use the host's display server
      - "QT_X11_NO_MITSHM=1"  # Fix for Qt and X11 shared memory issue

    # This will override command written in CMD in Dockerfile
    # - ROS launch will run a single ros master and the other nodes stated in the launch file
    # - We dont need to make a ros master in another container
    # By running source /app/devel/setup.bash, you're setting up the necessary environment variables to use ROS.
    command:  bash -c "source /app/devel/setup.bash && roslaunch hector_slam_launch tutorial.launch"
    network_mode: host

    # Allow python to print to output immediately
    tty: true
    stdin_open: true