services:
  cpu-node:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.pc-carto
    # 'volumes'maps the src directory in your workspace to the src directory in the container,
    # so that changes to your local files are reflected in the container.
    volumes:
      - ../lidar_mapping_ws/src:/app/src
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket
    devices:
      - /dev/dri:/dev/dri
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - "ROS_MASTER_URI=http://10.110.220.198:11311"
      # This is the ip of cpu_node. we need this to communicate with nodes in other container
      - "ROS_IP=10.110.220.198"

      - "ROS_PACKAGE_PATH=/app/src"
      - "DISPLAY=${DISPLAY}"

    # This will override command written in CMD in Dockerfile
    # - ROS launch will run a single ros master and the other nodes stated in the launch file
    # - We dont need to make a ros master in another container
    # By running source /app/devel/setup.bash, you're setting up the necessary environment variables to use ROS.
    command:  bash -c "source /app/devel/setup.bash && roslaunch gbot_core visualization.launch"
    network_mode: host

    # Allow python to print to output immediately
    tty: true
    stdin_open: true
    privileged: true

